### ISSUE TITLE
Need to add documentation first

### ISSUE THREAD

**Issue by multikitty** [charleskoffler/simol-language#2]
Hi, Charles. Thank you for your new idea and language.
In my opinion, it will be great if you add documentation of Simol language first.
Because, it is difficult (and a bit annoyed :)) to understand about Simol in readme file.
It is not enough with only readme file about Simol.
To get open source contributors, there is need to make documentation, official website and community, I think.
This is only my personal opinion.

Thanks

**Comment by multikitty** [comment]
For example, Mojo is still young, but it has active community to do effort as possible.
Are you the only one who developed this language?

**Comment by charleskoffler** [comment]
Hello multikitty. Thank you so much for taking time to look at that. I made simol alone, gathering idea for trying to improve object-oriented stuff usage. It was first for my personal usage, or my children. I wanted, on GitHub, to have a complete definition of the language, understandable, if possible, by AI-tools too. I know that I can do all other documentation, then, with pleasure. I need to understand, if it is possible, what are the topic and points that need to be explain in details. I had a website, but I thought that was a duplicate with GitHub. I'm going to make a new website, ok, my friend. And I'm going to add simple documentation at the same time, with great pleasure. Thank you so much for your interest

**Comment by andrew-johnson-4** [comment]
I don't really even need documentation if that is too much work right now. If we could see some program files with expected output that would help clarify a lot for me.

**Comment by charleskoffler** [comment]
I put code samples and eclipse projects, in directories: simol_design_patterns_examples, simol_simple_examples, simol_games_example. The expected output is quite simple, in general, with this basic examples. The snake games needs to be synchronized, I'll do it later. Thank you for your answer, that's great!

**Comment by charleskoffler** [comment]
I closed the issue. I improved the snake game and hello world examples. I added beginners documentation in /docs folder. The website will be exactly as the content of the beginners documentation, and it will be online as soon as possible. Thank you for your attention and support

**Comment by charleskoffler** [comment]
I added a website. Thank you for your support

**Comment by multikitty** [comment]
Hi, @charleskoffler . What is the website URL?

**Comment by charleskoffler** [comment]
Hi. The website is https://www.simol-lang.org . I just put there the documents of the repo. I could improve the appearance but perhaps later. The language itself is simple to grasp, be sure of this. The demonstration of his usefulness are complex, but not the language itself. Thank you my friend. You know just some feedback, even negative would be great for me. Think it could interest some people, but perhaps not everybody !
